### PR TITLE
fix: endless search for multiple-term queries

### LINKED ISSUE #38: ICD-10 API times out when searching long results
Searching icd codes with "longer" queries (> 6 terms), leads to endless searches.
This is due to the way icd10 API is designed, since it searches  for all possible combinations of terms.

Thus, max. amount of terms will be restricted by setting a env var `MAX_SEARCH_TERMS`

### PR DESCRIPTION
**Pull request by andreakreichgauer**
This PR fixes "endless" searches or time-outs due to long multiple-term queries. This closes #38 .

### CODE REVIEW

File: src/utils/HttpError.ts [hunk 1]
```diff
@@ -0,0 +1,8 @@
+export default class HTTPError extends Error {
```
Comment (rti) [inline src/utils/HttpError.ts:1]: The file name differs from the class name. To work on case sensitive file systems like ext4, the file should be renamed to `HTTPError`

Comment (andreakreichgauer) [reply src/utils/HttpError.ts]: 👍

**Review by rti — APPROVED** [review]
☀☀☀
